Create table VIDEOS_CATAGORY(
VCAT_ID NUMBER(9),
VCAT_NAME VARCHAR2(300) NOT NULL,
VCAT_DESCRIPTION VARCHAR2(1000),
Primary Key(VCAT_ID)
);

CREATE SEQUENCE VCAT_ID_seq
    INCREMENT BY 1
    START WITH 0
    MINVALUE 0
    MAXVALUE 9999999999999999;
-------------------------------------------------------------------------
Create table VIDEOS(
V_ID NUMBER(9) PRIMARY KEY,
V_NAME VARCHAR2(300) NOT NULL,
V_DESCRIPTION VARCHAR2(1000),
VCAT_ID NUMBER(9),
FOREIGN KEY(VCAT_ID) REFERENCES VIDEOS_CATAGORY(VCAT_ID)
);

CREATE SEQUENCE V_ID_seq
    INCREMENT BY 1
    START WITH 0
    MINVALUE 0
    MAXVALUE 9999999999999999;
-------------------------------------------------------------------------
Create table VIDEO_COPIES(
VCOP_ID NUMBER(9) PRIMARY KEY,
VCOP_PURCHASED DATE,
VCOP_STATUS VARCHAR2(1000),
V_ID NUMBER(9),
VCOP_RENT NUMBER NOT NULL,
FOREIGN KEY (V_ID) REFERENCES VIDEOS(V_ID)
);

CREATE SEQUENCE VCOP_ID_seq
    INCREMENT BY 1
    START WITH 0
    MINVALUE 0
    MAXVALUE 9999999999999999;
-------------------------------------------------------------------------
Create table CUSTOMERS(
C_ID NUMBER(9) PRIMARY KEY,
C_NAME VARCHAR2(300) NOT NULL,
C_TYPE VARCHAR2(30),
C_NAT_ID VARCHAR2(20) NOT NULL UNIQUE
);

CREATE SEQUENCE C_ID_seq
    INCREMENT BY 1
    START WITH 0
    MINVALUE 0
    MAXVALUE 9999999999999999;
-------------------------------------------------------------------------

CREATE TABLE RENTAL(
	R_ID NUMBER(9) PRIMARY KEY,
 	V_ID NUMBER(9), 
	C_ID NUMBER(9), 
	R_START_DATE DATE,
	R_END_DATE DATE,
	R_RENT NUMBER(9),
    
    FOREIGN KEY (V_ID) REFERENCES VIDEOS(V_ID),
    FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID)
);

CREATE SEQUENCE R_ID_seq
    INCREMENT BY 1
    START WITH 0
    MINVALUE 0
    MAXVALUE 9999999999999999;

-------------------------------------------------------------------------



